# Laboratorio

### Tarea 1. Introducción y Contexto del Negocio (Pegar el contenido del notion, hice un PDF en la carpeta de Docs)

### Tarea 2. Análisis Exploratorio de Datos (EDA) y preprocesamiento

#### 1. Importaciones importantes (SetUp)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.stats.outliers_influence import variance_inflation_factor

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (mean_absolute_error,mean_squared_error,r2_score)

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

#### Carga de Datos

In [5]:
import pandas as pd
from pathlib import Path

# Carpeta donde se encuentran los datasets, Lo busca para que no tengamos problemas en el repo
ruta_datos = Path("Data")

# Cargar los archivos Excel
historico = pd.read_excel(ruta_datos / "HISTORICO_SUERTES.xlsx")
ipsa = pd.read_excel(ruta_datos / "BD_IPSA_1940.xlsx")

# Verificar que se cargaron correctamente
print("Dimensiones de HISTORICO_SUERTES:", historico.shape)
print("Dimensiones de BD_IPSA_1940:", ipsa.shape)

display(historico.head())
display(ipsa.head())

Dimensiones de HISTORICO_SUERTES: (21027, 85)
Dimensiones de BD_IPSA_1940: (2187, 21)

,Período,Hacienda,Nombre,Zona,Tenencia,Suerte,Suelo,Area Neta,Dist Km,Variedad,Cod.Estado #,Cod.Estado,F.Siembra,D.S.,Ult.Riego,Edad Ult Cos,F.Ult.Corte,Destino 1=Semilla,Cod. T.Cultivo,Cultivo,Fec.Madur.,Producto,Dosis Madurante,Semanas mad.,TonUltCorte,TCH,TCHM,Ton.Azucar,Rdto,TAH,TAHM,Sac.Caña Precosecha,Edad.Precosecha,%Sac.Caña,%Sac.Muestreadora,%ATR,KATRHM,%Fibra Caña,%AR Jugo,%ME Min,%ME Veg,%ME Tot,Brix,Pureza,Vejez,Tipo Quema,T.Corte,Cerca de,Cosechó,Num.Riegos,M3 Riego,DDUlt.Riego,Lluvias (2 Meses Ant.),Lluvias Ciclo,Lluvias 0 -3,Lluvias tres a seis,Lluvias seis a nueve,Luvias 9 -FC,%Infest.Diatrea,Fosfato Jugo,Fert.Nitrogen.,Urea 46%,MEZ,Boro Granul.,MicroZinc,NITO_XTEND,Sul.Amonio,NITRAX-S,Vinaza,Codigo Estacion,Temp. Media 0-3,Temp. Media Ciclo,Temp Max Ciclo,Temp Min Ciclo,Humedad Rel Media 0-3,Humedad Rel Media Ciclo,Oscilacion Temp Med 0-3,Oscilacion Temp Ciclo,Sum Oscilacion Temp Ciclo,Radicion Solar 0-3,Radiacion Solar Ciclo,Precipitacion 0_3,Precipitacion Ciclo,Evaporacion 0-3,Evaporacion Ciclo
0,201701,80493,LA CONCHA,IP02,51.0,002A,CANTARINA,6.00,4.3,CC85-92,5,Corte 5,2010-08-20,NaN,NaT,12.81,2017-01-02,0,1.0,Normal,2016-11-04,BONUS 250 EC REGULADOR FISIOLÓGICO,1.0,8.428571,727.19,121.198333,9.461228,86.050,11.8332,14.341666,1.119567,16.8172,NaN,13.7582,13.508,15.1653,1434.823641,16.910,0.84,0.355,10.198,10.553,15.7464,87.2241,2.735,VERDE,MECANIZADO,El Cerrito,AI08,NaN,0.0,0,258.0,1038.0,0.0,454.0,102.0,482.0,NaN,178.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201701,81284,UKRANIA INCAUCA,IP05,81.0,039B,NaN,1.45,NaN,CC85-92,5,Corte 5,2011-01-27,NaN,NaT,11.14,2017-01-02,0,1.0,Normal,NaT,NaN,0.0,NaN,136.00,93.793103,8.419488,14.728,10.8294,10.157241,0.911781,NaN,NaN,12.8430,12.551,14.0410,1182.180399,16.936,0.55,2.298,7.273,9.571,15.2240,84.3602,73.823,Q.ACCIDENTAL,MANUAL,Candelaria,AI08,NaN,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,382.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201701,80203,EL AMPARO SAA,IP05,31.0,007,CORINTIAS,8.24,23.0,CC01-1228,4,Corte 4,2011-10-25,1.65,2016-09-17,12.32,2017-01-02,0,1.0,Normal,2016-11-04,BONUS 250 EC REGULADOR FISIOLÓGICO,1.1,8.428571,1436.62,174.347087,14.151549,145.268,10.1117,17.629611,1.430974,14.7749,12.02,11.9364,11.940,13.1236,1857.192723,15.512,0.61,3.000,9.323,12.323,14.1130,84.4527,2.108,VERDE,MECANIZADO,Palmira,AI08,5.0,48513.6,107,246.0,1002.0,106.0,326.0,113.0,457.0,NaN,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,201701,81380,SAN JUDAS INCAUCA,IP05,82.0,013A,NaN,1.05,66.5,CC01-1940,2,Corte 2,2014-03-08,NaN,NaT,9.79,2017-01-02,0,1.0,Normal,NaT,NaN,0.0,NaN,143.63,136.790476,13.972469,13.517,9.4109,12.873333,1.314947,NaN,NaN,11.2770,10.931,12.4820,1744.043640,17.621,0.67,0.140,6.788,6.927,13.6350,82.7062,64.614,Q.ACCIDENTAL,MANUAL,Corinto,AI08,NaN,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,278.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,201701,80298,JAVA,IP06,31.0,025A,GALPON,4.53,17.0,RB73-2223,3,Corte 3,2013-01-10,1.65,NaT,11.53,2017-01-02,0,1.0,Normal,NaT,NaN,0.0,NaN,512.20,113.068432,9.806455,42.505,8.2985,9.383002,0.813790,16.7662,NaN,10.2160,10.294,11.6030,1137.843039,14.352,0.95,0.592,2.939,3.531,12.9760,78.7299,71.021,Q.ACCIDENTAL,MANUAL,Guacari,AI08,NaN,0.0,0,138.0,991.0,264.0,255.0,188.0,284.0,NaN,244.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Unnamed: 0,NOME,FAZ,TAL,tipocorte,variedad,madurada,producto,dosismad,semsmad,edad,cortes,me,vejez,sacarosa,mes,periodo,TCH,lluvias,grupo_tenencia,pct_diatrea
0,11,AMAIME SILCA,81291,40,Mecanizado Verde,CC01-1940,SI,BONUS 250 EC REGULADOR FISIOLÓGICO,0.8,8.3,12.3,4,12.7,2.4,14.0,12,202012,112,137,3,6.2
1,12,AMAIME SILCA,81291,41,Mecanizado Verde,CC01-1940,SI,BONUS 250 EC REGULADOR FISIOLÓGICO,0.8,6.3,11.2,2,7.8,2.3,13.0,3,201903,157,0,3,3.5
2,13,AMAIME SILCA,81291,41,Mecanizado Verde,CC01-1940,SI,BONUS 250 EC REGULADOR FISIOLÓGICO,0.6,7.9,12.2,3,8.8,1.8,13.3,3,202003,167,68,3,4.3
3,15,AMAIME SILCA,81291,43,Mecanizado Verde,CC01-1940,SI,BONUS 250 EC REGULADOR FISIOLÓGICO,0.8,6.6,13.1,1,6.1,2.5,13.4,3,201903,156,0,3,3.5
4,16,AMAIME SILCA,81291,43,Mecanizado Verde,CC01-1940,SI,BONUS 250 EC REGULADOR FISIOLÓGICO,0.6,8.1,12.2,2,7.9,2.1,14.0,3,202003,151,68,3,4.3

#### 2. Cargar y conocer los datasets

In [6]:
print("=== HISTORICO_SUERTES ===")
historico.info()
print(historico.columns.tolist())

print("\n=== BD_IPSA_1940 ===")
ipsa.info()
print(ipsa.columns.tolist())

=== HISTORICO_SUERTES ===
<class 'pandas.DataFrame'>
RangeIndex: 21027 entries, 0 to 21026
Data columns (total 85 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Período                    21027 non-null  int64
 1   Hacienda                   21027 non-null  int64
 2   Nombre                     21027 non-null  str
 3   Zona                       21027 non-null  str
 4   Tenencia                   21026 non-null  float64
 5   Suerte                     21027 non-null  str
 6   Suelo                      17269 non-null  str
 7   Area Neta                  21027 non-null  float64
 8   Dist Km                    21022 non-null  float64
 9   Variedad                   21027 non-null  str
 10  Cod.Estado #               21027 non-null  int64
 11  Cod.Estado                 21027 non-null  str
 12  F.Siembra                  21027 non-null  datetime64[us]
 13  D.S.                       7168 non-null   str
 14  Ult.Riego                  8470 non-null   datetime64[us]
 15  Edad Ult Cos               21027 non-null  float64
 16  F.Ult.Corte                21027 non-null  datetime64[us]
 17  Destino 1=Semilla          21027 non-null  int64
 18  Cod. T.Cultivo             21025 non-null  float64
 19  Cultivo                    21025 non-null  str
 20  Fec.Madur.                 11252 non-null  datetime64[us]
 21  Producto                   11249 non-null  str
 22  Dosis Madurante            20923 non-null  float64
 23  Semanas mad.               11252 non-null  float64
 24  TonUltCorte                21027 non-null  float64
 25  TCH                        21027 non-null  float64
 26  TCHM                       21027 non-null  float64
 27  Ton.Azucar                 20786 non-null  float64
 28  Rdto                       20760 non-null  float64
 29  TAH                        20786 non-null  float64
 30  TAHM                       20786 non-null  float64
 31  Sac.Caña Precosecha        19929 non-null  float64
 32  Edad.Precosecha            8919 non-null   float64
 33  %Sac.Caña                  20578 non-null  float64
 34  %Sac.Muestreadora          19169 non-null  float64
 35  %ATR                       20505 non-null  float64
 36  KATRHM                     20505 non-null  float64
 37  %Fibra Caña                19169 non-null  float64
 38  %AR Jugo                   18903 non-null  float64
 39  %ME Min                    19305 non-null  float64
 40  %ME Veg                    19307 non-null  float64
 41  %ME Tot                    19307 non-null  float64
 42  Brix                       20760 non-null  float64
 43  Pureza                     20758 non-null  float64
 44  Vejez                      18582 non-null  float64
 45  Tipo Quema                 21027 non-null  str
 46  T.Corte                    21027 non-null  str
 47  Cerca de                   20901 non-null  str
 48  Cosechó                    21027 non-null  str
 49  Num.Riegos                 8438 non-null   float64
 50  M3 Riego                   21027 non-null  float64
 51  DDUlt.Riego                21027 non-null  int64
 52  Lluvias (2 Meses Ant.)     21027 non-null  float64
 53  Lluvias Ciclo              21027 non-null  float64
 54  Lluvias 0 -3               21027 non-null  float64
 55  Lluvias tres a seis        21027 non-null  float64
 56  Lluvias seis a nueve       21027 non-null  float64
 57  Luvias 9 -FC               21027 non-null  float64
 58  %Infest.Diatrea            5600 non-null   float64
 59  Fosfato Jugo               19169 non-null  float64
 60  Fert.Nitrogen.             0 non-null      float64
 61  Urea 46%                   723 non-null    float64
 62  MEZ                        971 non-null    float64
 63  Boro Granul.               1285 non-null   float64
 64  MicroZinc                  1149 non-null   float64
 65  NITO_XTEND                 3679 non-null   float64
 66  Sul.Amonio                 1357 non-null   float64
 67  NITRAX-S                   748 non-null    float64
 68  Vinaza                     4098 non-null   float64
 69  Codigo Estacion            6285 non-null   str
 70  Temp. Media 0-3            4530 non-null   float64
 71  Temp. Media Ciclo          4530 non-null   float64
 72  Temp Max Ciclo             4530 non-null   float64
 73  Temp Min Ciclo             4530 non-null   float64
 74  Humedad Rel Media 0-3      4530 non-null   float64
 75  Humedad Rel Media Ciclo    4530 non-null   float64
 76  Oscilacion Temp Med 0-3    4530 non-null   float64
 77  Oscilacion Temp Ciclo      4530 non-null   float64
 78  Sum Oscilacion Temp Ciclo  0 non-null      float64
 79  Radicion Solar 0-3         4530 non-null   float64
 80  Radiacion Solar Ciclo      4530 non-null   float64
 81  Precipitacion 0_3          4530 non-null   float64
 82  Precipitacion Ciclo        4530 non-null   float64
 83  Evaporacion 0-3            4530 non-null   float64
 84  Evaporacion Ciclo          4530 non-null   float64
dtypes: datetime64[us](4), float64(62), int64(5), str(14)
memory usage: 15.6 MB
['Período', 'Hacienda', 'Nombre', 'Zona', 'Tenencia', 'Suerte', 'Suelo', 'Area Neta', 'Dist Km', 'Variedad', 'Cod.Estado #', 'Cod.Estado', 'F.Siembra', 'D.S.', 'Ult.Riego', 'Edad Ult Cos', 'F.Ult.Corte', 'Destino 1=Semilla', 'Cod. T.Cultivo', 'Cultivo', 'Fec.Madur.', 'Producto', 'Dosis Madurante', 'Semanas mad.', 'TonUltCorte', 'TCH', 'TCHM', 'Ton.Azucar', 'Rdto', 'TAH', 'TAHM', 'Sac.Caña Precosecha', 'Edad.Precosecha', '%Sac.Caña', '%Sac.Muestreadora', '%ATR', 'KATRHM', '%Fibra Caña', '%AR Jugo', '%ME Min', '%ME Veg', '%ME Tot', 'Brix', 'Pureza', 'Vejez', 'Tipo Quema', 'T.Corte', 'Cerca de', 'Cosechó', 'Num.Riegos', 'M3 Riego', 'DDUlt.Riego', 'Lluvias (2 Meses Ant.)', 'Lluvias Ciclo', 'Lluvias 0 -3', 'Lluvias tres a seis', 'Lluvias seis a nueve', 'Luvias 9 -FC', '%Infest.Diatrea', 'Fosfato Jugo', 'Fert.Nitrogen.', 'Urea 46%', 'MEZ', 'Boro Granul.', 'MicroZinc', 'NITO_XTEND', 'Sul.Amonio', 'NITRAX-S', 'Vinaza', 'Codigo Estacion', 'Temp. Media 0-3', 'Temp. Media Ciclo', 'Temp Max Ciclo', 'Temp Min Ciclo', 'Humedad Rel Media 0-3 ', 'Humedad Rel Media Ciclo', 'Oscilacion Temp Med 0-3', 'Oscilacion Temp Ciclo', 'Sum Oscilacion Temp Ciclo', 'Radicion Solar 0-3', 'Radiacion Solar Ciclo', 'Precipitacion 0_3', 'Precipitacion Ciclo', 'Evaporacion 0-3', 'Evaporacion Ciclo']

=== BD_IPSA_1940 ===
<class 'pandas.DataFrame'>
RangeIndex: 2187 entries, 0 to 2186
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      2187 non-null   int64
 1   NOME            2187 non-null   str
 2   FAZ             2187 non-null   int64
 3   TAL             2187 non-null   object
 4   tipocorte       2187 non-null   str
 5   variedad        2187 non-null   str
 6   madurada        2187 non-null   str
 7   producto        2187 non-null   str
 8   dosismad        2187 non-null   float64
 9   semsmad         2187 non-null   float64
 10  edad            2187 non-null   float64
 11  cortes          2187 non-null   int64
 12  me              2187 non-null   float64
 13  vejez           2187 non-null   float64
 14  sacarosa        2187 non-null   float64
 15  mes             2187 non-null   int64
 16  periodo         2187 non-null   int64
 17  TCH             2187 non-null   int64
 18  lluvias         2187 non-null   int64
 19  grupo_tenencia  2187 non-null   int64
 20  pct_diatrea     2187 non-null   float64
dtypes: float64(7), int64(8), object(1), str(5)
memory usage: 520.2+ KB
['Unnamed: 0', 'NOME', 'FAZ', 'TAL', 'tipocorte', 'variedad', 'madurada', 'producto', 'dosismad', 'semsmad', 'edad', 'cortes', 'me', 'vejez', 'sacarosa', 'mes', 'periodo', 'TCH', 'lluvias', 'grupo_tenencia', 'pct_diatrea']

#### 3. Analisis y deteccion de datos faltantes

##### 3.1. Porcentaje de valores nulos por columna

In [ ]:
#Adaptado del taller de Scouting
def analizar_faltantes(df, nombre):
    resultado = pd.DataFrame({
        "Valores nulos": df.isna().sum(),
        "Porcentaje nulo": df.isna().mean() * 100,
        "Tipo de dato": df.dtypes.astype(str),
        "Valores únicos": df.nunique(dropna=True)})

    resultado = resultado.sort_values("Porcentaje nulo", ascending=False)
    print(f"\nDataset: {nombre}")
    display(resultado.round(2))
    return resultado

faltantes_historico = analizar_faltantes(historico, "HISTORICO_SUERTES")

faltantes_ipsa = analizar_faltantes(ipsa, "BD_IPSA_1940")

In [ ]:
def graficar_faltantes(df, nombre):
    porcentajes = df.isna().mean().mul(100)
    porcentajes = porcentajes[porcentajes > 0].sort_values()

    if porcentajes.empty:
        print(f"{nombre}: no hay valores nulos.")
        return

    porcentajes.plot(
        kind="barh",
        figsize=(9, max(4, len(porcentajes) * 0.3))
    )
    plt.xlabel("Porcentaje de valores faltantes (%)")
    plt.title(f"Valores faltantes - {nombre}")
    plt.tight_layout()
    plt.show()

graficar_faltantes(historico, "HISTORICO_SUERTES")
graficar_faltantes(ipsa, "BD_IPSA_1940")

##### 3.2. ¿Cómo interpretar los resultados? (Por realizar)

##### 3.3. Duplicados y valores inconsistentes

In [ ]:
def revisar_calidad(df, nombre):
    print(f"\n--- {nombre} ---")
    print("Filas duplicadas:", df.duplicated().sum())
    print("Filas:", len(df))
    print("Columnas:", len(df.columns))

    display(df.describe(include="all").T)

revisar_calidad(historico, "HISTORICO_SUERTES")
revisar_calidad(ipsa, "BD_IPSA_1940")

#### 4. Selección y justificación de variables

#### 5. Distribuciones de TCH y sacarosa

In [ ]:
#Hay qye identificar los nombres exactos de las columnas objetivo: